INSERT INTO products (product_name, price, quantity, image_url, product_type, description) VALUES
    ('Classic Hoodie', 39.99, 25, '/images/products/classichoodie.jpg', 'clothing', 'Finally block out your neighbors saxophone practice, your coworkers loud phone calls, and that one mystery bird outside your window at 5 a.m. Slip these on, and enjoy your own personal silent movie — starring you, ignoring the world.'),
    ('Wireless Mouse', 24.99, 50, '/images/products/wirelessmouse.jpg', 'electronics', ' Finally cut the cord — no more getting tangled like last nights spaghetti. Smooth, fast, and so precise it might just help you finally hit "save" instead of "close without saving." Your desks new best friend.'),
    ('USB-C Charger 65W', 29.99, 40, 'images/products/usbcharger.jpg', 'electronics', 'No description need here. You know what it does and you know you need it.'),
    ('Noise Cancelling Headphones', 89.95, 15, '/images/products/headphones.jpg', 'electronics', 'Finally block out your neighbors saxophone practice, your coworkers loud phone calls, and that one mystery bird outside your window at 5 a.m. Slip these on, and enjoy your own personal silent movie — starring you, ignoring the world.'),
    ('Stainless Steel Water Bottle', 19.99, 60, '/images/products/waterbottle.jpg', 'wellness', 'This sleek stainless steel water bottle keeps your drinks icy cold or lava-level hot for hours — because nobody likes lukewarm coffee or sad, tepid water. Take it to the gym, the office, or on your quest to finally fold that pile of laundry. Hydrate like a champ!'),
    ('Laptop Backpack', 49.99, 20, '/images/products/backpack.jpg', 'general', 'Carries your laptop, snacks, and questionable life choices — all in one sleek, comfy package. Great for commuting, traveling, or just pretending youre organized. Bonus: it makes you look like you actually know where youre going.'),
    ('Yoga Mat', 25.00, 30, '/images/products/yogamat.jpg', 'wellness', 'Look, its a yoga mat. Its not going to align your chakras for you or whisper sweet “oms” in your ear — but it will keep your knees from crying during cat-cow'),
    ('Bluetooth Speaker', 34.99, 10, ' /images/products/bluetoothspeaker.jpg', 'electronics', 'Turns any room, park, or shower into your personal concert venue. Crisp sound, deep bass, and zero awkward aux cord fights. Just beware: once you hit play, your friends might never leave.'),
    ('Portable SSD 1TB', 99.99, 0, '/images/products/ssdharddrive.jpg', 'electronics', 'Tiny enough to fit in your pocket, but big enough to hold all your photos, movies, unfinished novels, and that giant folder labeled "Important Stuff." Sure it is. Anyway, fast, sleek, and so reliable you will wonder why you ever trusted those old dusty hard drives.');
